name: Build npm package

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'The name of the project'
        required: true
        type: string
      version:
        description: 'The build version'
        required: true
        type: string
  workflow_call:
    inputs:
      project:
        description: 'The name of the project'
        required: true
        type: string
      version:
        description: 'The build version'
        required: true
        type: string

jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@${{ github.repository_owner }}'

    - name: Download typescript model files
      uses: actions/download-artifact@v4
      with:
        name: model-typescript-artifact
    
    - name: Generate index.ts for TypeScript models
      run: node generate-index.js
      working-directory: ${{ github.workspace }}/npm.
    
    - name: Build npm package
      run: |
        # Use regular npm install instead of npm ci since no package-lock exists
        npm install
        # Fix: correct syntax for specifying tsconfig with tsc
        npm run build || (echo "TypeScript compilation failed" && npx tsc --listFiles --pretty)
      working-directory: ${{ github.workspace }}/.
    
    - name: Publish to GitHub Packages
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES }}
      working-directory: ${{ github.workspace }}/.
